### ISSUE TITLE
[Question] What versions of node does this work with?

### ISSUE THREAD

**Issue by Asheq** [neovim/node-client#144]
I noticed that `package.json` has [this](https://github.com/neovim/node-client/blob/37a5a6eea7315b330130804510481813235a03a9/package.json#L50) line:

```
    "node": "10.18.0",
```

Does node have to be this exact version? Or is there a range of valid versions?

Thanks for your help!

**Comment by rhysd** [comment]
I think the `volta` section is not maintained well because (I guess) none of maintainers is a user of Volta.

There is no reason to fix the version completely. At least this repository supports active LTS versions v10 and v12. They are tested on CI. Making changes at package.json for better node versions in `volta` section is welcome.

**Comment by justinmk** [comment]
https://github.com/neovim/node-client/commit/5118d3525e335aa9422c40ccd1a3bcb90b5c1a13

AFAICT volta is just some tool that makes it easy to install ... stuff? Those lines are not a declaration of required versions of anything?

**Comment by billyvg** [comment]
I think this issue still deserves an answer, regardless of the misinterpretation of `volta`.  Like @rhysd said, we should aim to support active LTS versions.

**Comment by rhysd** [comment]
From [the guide](https://docs.volta.sh/guide/understanding) I understood that the `volta` section is for development. It does not specify the node version of package user, but package developer. I misunderstood.

I think adding `engines` section to package.json would be useful for package users.

https://docs.npmjs.com/files/package.json#engines
