### ISSUE TITLE
Reduce complexity of the plugin API 

### ISSUE THREAD

**Issue by kutsan** [neovim/node-client#43]
I think API should be vanilla NodeJS friendly. Babel and friends don't help developers at this point and using legacy decorators and other early features shouldn't be recommended. Please keep the API simple.

I could write the plugins like this now without Babel configurations but decorators looks bad to be honest.

```javascript
const { Plugin, Command } = require('neovim')

class TestPlugin {
	splitV() {
		this.nvim.command('vsplit')
	}
}

Command('Vsplit')(TestPlugin.prototype.splitV)

module.exports = Plugin({ dev: true })(TestPlugin)
```

**Comment by billyvg** [comment]
I agree, I'll explore a simpler API for creating plugins

**Comment by kutsan** [comment]
Thanks for your answer. I'm looking forward to.

**Comment by janlazo** [comment]
Doesn't work in Windows. I've tried on node 6.91 and current LTS (8.9.1).

**Comment by kutsan** [comment]
@janlazo I wish I could help but I don't use and know Windows, but it should work; I don't think the problem this about the code sample. For what it's worth, that's not this issue for. I think you should create an another issue for that, with your exact steps.

**Comment by janlazo** [comment]
This works for me in Windows. I can't register commands yet.

```javascript
const socket = process.env.NVIM_LISTEN_ADDRESS;
const neovim = require('neovim');
const nvim = neovim.attach({socket: socket});

class TestPlugin {
    echoHello() {
        this.nvim.command('echom "hello"')
    }
}

neovim.Command('Hello')(TestPlugin.prototype.echoHello);
const PluginClass = neovim.Plugin(TestPlugin);
const plugin = new PluginClass(nvim);
plugin.echoHello();
```

**Comment by justinmk** [comment]
Is there a way to avoid users/plugin authors needing to manually manage the `$NODE_PATH` ?

In the python-client we mangle the import path dynamically.  Although virtualenv's must be managed by the user (obviously).

**Comment by billyvg** [comment]
@janlazo You shouldn't need to do `jobstart(['node', 'path/to/plugin.js'])`, that's what the node host is supposed to handle.

**Comment by janlazo** [comment]
@billyvg What about plugins outside of `rplugin/node`?

**Comment by billyvg** [comment]
What's the use case where it's outside of `rplugin`?

**Comment by billyvg** [comment]
How do you feel about something like this:

```javascript
const NeovimPlugin = require('neovim/plugin');

const plugin = NeovimPlugin.create('PluginName', {dev: true});

plugin.function('FuncName', {options}, function() {
});

plugin.command('commandName', {options}, function() {
});

plugin.autocmd('BufEnter', {pattern: '*.js', eval: 'expand("<afile>")', sync: true }, function() {
});

module.exports = plugin;
```

**Comment by kutsan** [comment]
@billyvg What do you think about this one? Just sharing it for the sake of more ideas.

```js
class TestPlugin extends Plugin {
	constructor() {
		super()

		this.register({
			as: 'plugin',
			name: 'TestPlugin'
		})
	}

	testFunc() {
		this.register({
			as: 'function',
			name: 'FuncName'
		})

		// ...
	}
}
```

**Comment by janlazo** [comment]
My experience with javascript is mostly on ES5 in the browser so I'm fine with a few global function/class/object to interact with the client to avoid global `require` as long as I don't have to use an IIFE. I prefer to not use a class because Vimscript doesn't have classes but if that's what it takes to hide `nvim` or avoid IIFE, I can live with it.

**Comment by kutsan** [comment]
> If we're using classes, I prefer to have a custom class constructor on top of base plugin class for more control on the initial state.

@janlazo Like my example?

**Comment by janlazo** [comment]
Yes, but I'm not sure about `this.register` because it seems too generic to expose. I prefer passing an object to `super()` to hide this. Worst case, the user can use `this.nvim.command` to define commands, functions, etc. after creating a new instance of the user plugin. Maybe there's a way to broadcast that event or perhaps add a promise handler.

**Comment by janlazo** [comment]
@justinmk `npm link neovim` reduces the need to set `NODE_PATH` but that creates a local `node_modules` and copies a subset of the required files (and dependencies) on Windows instead of creating a symlink. `ln.exe -s` behaves the same (https://github.com/junegunn/fzf/pull/933#issuecomment-306351046). It's best to stick with `NODE_PATH` if the user doesn't require package.json for dependencies.

Reference: https://docs.npmjs.com/cli/link

**Comment by justinmk** [comment]
Sounds good. In any case this is done by node-client, right? Plugin devs and users don't need to do this explicitly.

**Comment by jpstone** [comment]
Out of curiosity, why not let developers worry about the implementation and simply provide them an object from which to use? 

```js
import { Command } from 'neovim';

export default function myPlugin(nvim) {
  return {
    splitV: Command('Vsplit')(() => {
      nvim.command('vsplit');
    }),
  }
}
```

**Comment by simlrh** [comment]
I don't know if any work has been done on this, but I'll offer another suggestion! My preference would be strongly against any global object being either injected or required. 

Defining a plugin by exporting a single function which takes nvim as an argument would be ideal for testing via dependency injection etc. The functions to register commands could exist on the nvim object.

This would allow whatever programming style you prefer, functional or OO, eg:
```
function someCommand() {}
function someAutocmd() {}

class StatefulThing {
  aMethod() {}
}

class AnotherClass {
  constructor(nvim) {
    nvim.registerCommand('AnotherCommand', [this, this.anotherMethod]);
  }
  anotherMethod() {}
}

module.exports = (nvim) => {
  nvim.registerCommand('CommandName', someCommand, { option: true });
  nvim.registerAutocmd('BufWritePre', someAutocmd, { pattern: '*' });

  const stateful = new StatefulThing();
  nvim.registerCommand('AnotherCommand', [stateful, stateful.aMethod]);

  const anotherInstance = new AnotherClass(nvim);
};
```

I would also love an official way to listen for arbitrary events sent by rpcnotify. I'm currently hacking around this with the following:

```
@Plugin({ dev: true })
export default class ListenerPlugin {
  @Command('AddListener')
  async addListener() {
    this.nvim.command(`au CursorMoved * call rpcnotify(${this.nvim._channel_id}, '${PLUGIN_PATH}:command:Handler', 'Test')`);
  }

  @Command('Handler')
  async handler(...args) {
    console.log(args);
  }
}
```

It would be nice to have `nvim.registerRPCHandler('EventName', fn)` instead.

I'm happy to put in a PR for a different plugin API if it won't be duplicating work.

**Comment by chemzqm** [comment]
I'm ok with current API, but the code transform is required at this time, it makes it harder to write and debug, a functional API would be nice to have.

**Comment by kutsan** [comment]
@chemzqm As I mentioned in my first code example in this issue, you don't have to transform your code with Babel, but if you don't you have to write your decorators like `Command('Vsplit')(TestPlugin.prototype.splitV)`. Are you still okay with that? What approach do you prefer instead of decorators?

**Comment by chemzqm** [comment]
@kutsan I would use babel instead of write code like `Command('Vsplit')(TestPlugin.prototype.splitV)` it's not my taste.  I've been using mobxjs/mobx for a long time, so I'm comfortable with the decorators.
Maybe node-client could provide a command that wraps babel to use `transform-es2015-modules-commonjs` `transform-decorators-legacy` for code transform, so that the plugin author could avoid  install them for every plugin.

**Comment by kutsan** [comment]
@chemzqm I don't think providing a wrapper around babel is a good idea.

**Comment by janlazo** [comment]
Now that #54 is merged, how does this affect local testing such as https://github.com/neovim/neovim/blob/master/test/functional/provider/nodejs_spec.lua? I worked on this with @justinmk but I'm not satisfied with the global dependency of the `neovim` module because it leaks the abstraction of the nodejs host into the plugin. Is `require('neovim')` still required in the user plugin?

**Comment by kutsan** [comment]
Since @simlrh did the great job with making https://github.com/neovim/node-client/pull/54 I think we can close this issue now. 🎉

**Comment by janlazo** [comment]
Is it ready for public testing? There's no patch release.
